version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 6000:6000
    volumes:
      - ./:/usr/src/app
    command: yarn run dev
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
